plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    log4jConfigs.setFrom(file('src/dev/log4j.xml'))

    runs {
        configureEach {
            vmArg '-Dfabric-tag-conventions-v2.missingTagTranslationWarning=SILENCED'
        }

        client {
            programArg '--username'
            programArg 'DevPlayer'
            programArg '--uuid'
            programArg '00000000-0000-0000-0000-000000000001'
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            loader_version         : loader_version,
            min_loader_version     : min_loader_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            minecraft_version_range: minecraft_version_range,
            logo                   : logo,
            home_page              : home_page
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir(generateModMetadata)

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = file("repo").toURI()
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
